# This is a basic workflow to help you get started with Actions

name: list

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/*'
      - 'config.json'
      - 'README.md'
      - 'list/**'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  list:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Encoding
        run: |
          git config --global i18n.logoutputencoding utf-8
          git config --global i18n.commitencoding utf-8
          git config --global core.quotepath false
          export LESSCHARSET=utf-8
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # OR "2" -> To retrieve the preceding commit.
      - name: List files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          # base_sha: ${{ steps.sha.outputs.content }}
          fetch_depth: 1
          quotepath: "false"
          include_all_old_new_renamed_files: true
          files_ignore: |
            config.json
            README.md
            .github/**
      - name: Echo files
        run: |
          echo ${{ steps.changed-files.outputs.added_files }} >> add.list
          echo ${{ steps.changed-files.outputs.all_old_new_renamed_files }} >> rename.list
          echo ${{ steps.changed-files.outputs.deleted_files }} >> delete.list
      - name: Update
        env:
          CSRF: ${{ secrets.CSRF }}
          SESSDATA: ${{ secrets.SESSDATA }}
        run: |
          cd .github/workflows
          npm i axios
          node list.js
      - name: Push
        # run: |
        #   git status
        #   rm -rf rename.list add.list delete.list .github/workflows/node_modules/ .github/workflows/package-lock.json .github/workflows/package.json
        #   git config user.email "github_temp@inkroom.cn"
        #   git config user.name "Action Robot"
        #   git add list
        #   git commit -m "update list"
        #   git push
        uses: actions-x/commit@v6
        with:
          email: github_temp@inkroom.cn
          name: Action Robot
          message: "Update List By Action Robot"
          branch: master
          files: list
